name: Build Decord with CUDA (Windows)

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install CUDA Toolkit
      run: |
        choco install cuda -y --force
        echo "CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.9" >> $env:GITHUB_ENV
        echo "PATH=$env:PATH;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.9\bin" >> $env:GITHUB_ENV
      shell: powershell
      
    - name: Verify CUDA Installation
      run: |
        echo "CUDA_PATH: $env:CUDA_PATH"
        echo "PATH: $env:PATH"
        nvcc --version
        
        # Check CUDA installation structure
        echo "Checking CUDA installation structure..."
        if (Test-Path "$env:CUDA_PATH") {
          echo "CUDA root directory exists: $env:CUDA_PATH"
          
          # Check for lib directory
          if (Test-Path "$env:CUDA_PATH\lib\x64") {
            echo "CUDA lib\x64 directory exists"
            echo "Available libraries in lib\x64:"
            Get-ChildItem "$env:CUDA_PATH\lib\x64\*.lib" | Select-Object Name
          } else {
            echo "Warning: CUDA lib\x64 directory not found"
          }
          
          # Check for include directory
          if (Test-Path "$env:CUDA_PATH\include") {
            echo "CUDA include directory exists"
          } else {
            echo "Warning: CUDA include directory not found"
          }
        } else {
          Write-Error "CUDA installation directory not found at: $env:CUDA_PATH"
          exit 1
        }
      shell: powershell

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Build Tools
      run: |
        pip install wheel numpy cython
        choco install cmake -y

    - name: Download FFmpeg libs
      run: |
        # Download FFmpeg development libraries with retry logic
        $maxRetries = 3
        $retryCount = 0
        
        do {
          try {
            Write-Host "Attempting to download FFmpeg dev libraries (attempt $($retryCount + 1)/$maxRetries)..."
            Invoke-WebRequest -Uri "https://github.com/zhreshold/decord-distro/files/5314603/ffmpeg-4.2.1-win64-dev.zip" -OutFile "ffmpeg-4.2.1-win64-dev.zip" -UseBasicParsing
            
            # Verify the download
            if ((Get-Item "ffmpeg-4.2.1-win64-dev.zip").Length -gt 1MB) {
              Write-Host "FFmpeg dev libraries downloaded successfully"
              break
            } else {
              throw "Downloaded file is too small, likely corrupted"
            }
          } catch {
            Write-Host "Download failed: $($_.Exception.Message)"
            $retryCount++
            if ($retryCount -lt $maxRetries) {
              Write-Host "Retrying in 5 seconds..."
              Start-Sleep -Seconds 5
            }
          }
        } while ($retryCount -lt $maxRetries)
        
        if ($retryCount -eq $maxRetries) {
          Write-Error "Failed to download FFmpeg dev libraries after $maxRetries attempts"
          exit 1
        }
        
        # Download FFmpeg shared libraries with retry logic
        $retryCount = 0
        do {
          try {
            Write-Host "Attempting to download FFmpeg shared libraries (attempt $($retryCount + 1)/$maxRetries)..."
            Invoke-WebRequest -Uri "https://github.com/vmlankub/CloudFiles/raw/5ec06ef8b7568cc3b84d310ef146c63c5e693b54/ffmpeg/ffmpeg-4.2.1-win64-shared.zip" -OutFile "ffmpeg-4.2.1-win64-shared.zip" -UseBasicParsing
            
            # Verify the download
            if ((Get-Item "ffmpeg-4.2.1-win64-shared.zip").Length -gt 1MB) {
              Write-Host "FFmpeg shared libraries downloaded successfully"
              break
            } else {
              throw "Downloaded file is too small, likely corrupted"
            }
          } catch {
            Write-Host "Download failed: $($_.Exception.Message)"
            $retryCount++
            if ($retryCount -lt $maxRetries) {
              Write-Host "Retrying in 5 seconds..."
              Start-Sleep -Seconds 5
            }
          }
        } while ($retryCount -lt $maxRetries)
        
        if ($retryCount -eq $maxRetries) {
          Write-Error "Failed to download FFmpeg shared libraries after $maxRetries attempts"
          exit 1
        }
      shell: powershell

    - name: Extract FFmpeg libs
      shell: powershell
      run: |
        # Verify zip files before extraction
        Write-Host "Verifying downloaded zip files..."
        
        try {
          # Test the dev zip file
          $devZip = "ffmpeg-4.2.1-win64-dev.zip"
          if (Test-Path $devZip) {
            Write-Host "Testing $devZip integrity..."
            Add-Type -AssemblyName System.IO.Compression.FileSystem
            $zip = [System.IO.Compression.ZipFile]::OpenRead($devZip)
            $zip.Dispose()
            Write-Host "$devZip is valid"
          } else {
            throw "$devZip not found"
          }
          
          # Test the shared zip file
          $sharedZip = "ffmpeg-4.2.1-win64-shared.zip"
          if (Test-Path $sharedZip) {
            Write-Host "Testing $sharedZip integrity..."
            $zip = [System.IO.Compression.ZipFile]::OpenRead($sharedZip)
            $zip.Dispose()
            Write-Host "$sharedZip is valid"
          } else {
            throw "$sharedZip not found"
          }
          
          # Extract the files
          Write-Host "Extracting FFmpeg libraries..."
          Expand-Archive -LiteralPath $devZip -DestinationPath d:\ -Force
          Expand-Archive -LiteralPath $sharedZip -DestinationPath d:\ -Force
          
          Write-Host "FFmpeg libraries extracted successfully"
          
        } catch {
          Write-Error "Failed to extract FFmpeg libraries: $($_.Exception.Message)"
          Write-Host "Attempting alternative extraction method..."
          
          # Try using 7-Zip if available
          try {
            choco install 7zip -y
            & "C:\Program Files\7-Zip\7z.exe" x $devZip -od:\ -y
            & "C:\Program Files\7-Zip\7z.exe" x $sharedZip -od:\ -y
            Write-Host "Alternative extraction successful"
          } catch {
            Write-Error "All extraction methods failed. Please check the FFmpeg download sources."
            exit 1
          }
        }

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        echo "Using CUDA_PATH: $env:CUDA_PATH"
        cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_CXX_FLAGS="/DDECORD_EXPORTS" -DCMAKE_CONFIGURATION_TYPES="Release" -DUSE_CUDA=ON -DCUDAToolkit_ROOT="$env:CUDA_PATH" -DCMAKE_CUDA_ARCHITECTURES="75;80;86;89;90" -DFFMPEG_INCLUDE_DIR="d:/ffmpeg-4.2.1-win64-dev/include" -DFFMPEG_LIBRARIES="d:/ffmpeg-4.2.1-win64-dev/lib/*.lib" ..
      shell: powershell

    - name: Build
      run: |
        cd build
        cmake --build . --config Release
      shell: powershell

    - name: Build Python wheel
      run: |
        cd python
        python setup.py bdist_wheel
      shell: powershell

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: decord-cuda-wheel
        path: python/dist/*.whl

    - name: Sanity test
      run: |
        cd python/dist
        $wheel = Get-ChildItem *.whl | Select-Object -First 1
        pip install $wheel.FullName --force-reinstall
        python -c "import decord; print('Decord version:', decord.__version__); print('CUDA support:', hasattr(decord, 'gpu')); import decord.ndarray as nd; print('NDArray module loaded successfully')"
      shell: powershell
